/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseDrag: typeof import('./../components/BaseDrag.vue')['default']
    CopyToClipboardButton: typeof import('./../components/CopyToClipboardButton.vue')['default']
    Error: typeof import('./../views/Error.vue')['default']
    HelloWorld: typeof import('./../views/HelloWorld.vue')['default']
    Maimai: typeof import('./../views/maimai.vue')['default']
    Menus: typeof import('./../components/Menus.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDataTable: typeof import('naive-ui')['NDataTable']
    NDatePicker: typeof import('naive-ui')['NDatePicker']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NDivider: typeof import('naive-ui')['NDivider']
    NFlex: typeof import('naive-ui')['NFlex']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NGi: typeof import('naive-ui')['NGi']
    NGradientText: typeof import('naive-ui')['NGradientText']
    NGrid: typeof import('naive-ui')['NGrid']
    NInput: typeof import('naive-ui')['NInput']
    NInputNumber: typeof import('naive-ui')['NInputNumber']
    NLable: typeof import('naive-ui')['NLable']
    NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NModal: typeof import('naive-ui')['NModal']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    NSpace: typeof import('naive-ui')['NSpace']
    NTable: typeof import('naive-ui')['NTable']
    NTimePicker: typeof import('naive-ui')['NTimePicker']
    NyanCat: typeof import('./../views/NyanCat.vue')['default']
    Random: typeof import('./../views/Random/Random.vue')['default']
    RandomString: typeof import('./../views/Random/RandomString.vue')['default']
    RandomUserName: typeof import('./../views/Random/RandomUserName.vue')['default']
    RedirectTo: typeof import('./../components/RedirectTo.vue')['default']
    TimeInterval: typeof import('./../views/TimeInterval.vue')['default']
    WindowProvider: typeof import('./../components/WindowProvider/WindowProvider.vue')['default']
  }
}
